name: customer
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  # firebase
  firebase_auth: ^4.9.0
  cloud_firestore: ^4.9.1
  firebase_core: ^2.15.1
  google_sign_in: ^6.1.5
  firebase_messaging: ^14.6.7
  firebase_storage: ^11.2.6
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  geoflutterfire2: ^2.3.15
  geocoding: ^2.1.0
  flutter_local_notifications: ^15.1.1

  cached_network_image: ^3.2.3
  flutter_svg: ^2.0.7
  shared_preferences: ^2.2.1
  url_launcher: ^6.1.14
  uuid: ^4.0.0
  http: ^0.13.1
  google_fonts: ^4.0.4
  get: 
  pin_code_fields: ^8.0.1
  intl: ^0.18.1
  flutter_easyloading: ^3.0.5
  country_code_picker: ^3.0.0
  google_maps_flutter: ^2.5.0
  geolocator: ^9.0.2
  place_picker: ^0.10.0
  flutter_polyline_points: ^1.0.0
  flutter_rating_bar: ^4.0.1
  bottom_picker: ^2.0.4
  flutter_google_places_hoc081098: ^1.2.0
  flutter_dash: ^1.0.0
  provider: ^6.0.5
  dotted_border: ^2.0.0+3
  clipboard: ^0.1.3
  image_picker: ^1.0.4
  flutterflow_paginate_firestore: ^1.0.3+1
  video_thumbnail: ^0.5.3
  path_provider: ^2.1.1
  photo_view: ^0.14.0
  video_player: ^2.7.1
  flutter_email_sender: ^6.0.1
  flutter_html: any
  flutter_share: ^2.0.0
  map_launcher: ^2.5.0+1

  #payment dependency
  flutter_stripe: ^9.5.0+1
  mercadopago_sdk: ^1.3.0
  flutterwave_standard: ^1.0.7
  paytm_allinonesdk: ^1.2.1
  razorpay_flutter: ^1.3.5
  flutter_paypal_native: ^2.0.1
  

dependency_overrides:
  webview_flutter: ^4.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_automation: ^2.0.0
  flutter_lints: ^2.0.2
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: any


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_logo.png"

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
