// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCk7j71Y4BvjGDpY3KBQ5cze8iAYJpTp98',
    appId: '1:1089834042923:web:1d4bfe2dcdb84b03fb4c6e',
    messagingSenderId: '1089834042923',
    projectId: 'miles-b6fcd',
    authDomain: 'miles-b6fcd.firebaseapp.com',
    storageBucket: 'miles-b6fcd.appspot.com',
    measurementId: 'G-2789TJN2V7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBnFN5CNfkFn1n6TUzXgE8oCquOhRr3a4',
    appId: '1:1089834042923:android:92b3e7506f5a732cfb4c6e',
    messagingSenderId: '1089834042923',
    projectId: 'miles-b6fcd',
    storageBucket: 'miles-b6fcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjjQ-IAovGY8gDAkEIJ7_YGcC57kq9kX0',
    appId: '1:1089834042923:ios:1765f24c2c1c1971fb4c6e',
    messagingSenderId: '1089834042923',
    projectId: 'miles-b6fcd',
    storageBucket: 'miles-b6fcd.appspot.com',
    iosClientId: '1089834042923-ejd1vqmchih7m3vvlnr77c7rf4m2o1h4.apps.googleusercontent.com',
    iosBundleId: 'com.Mile.customer',
  );
}
