// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGdRCnDwO7rEWlc29koqqI3hCg3-zqCng',
    appId: '1:581288455500:android:5877f4c361ad15fe07f3e9',
    messagingSenderId: '581288455500',
    projectId: 'mile-e1045',
    storageBucket: 'mile-e1045.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzJvoEu7EeF0lBrquiaua7tX0EMGC1uNQ',
    appId: '1:581288455500:ios:d121c21d1feeb10c07f3e9',
    messagingSenderId: '581288455500',
    projectId: 'mile-e1045',
    storageBucket: 'mile-e1045.appspot.com',
    iosBundleId: 'com.mileapp.customer',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbznMLNkY4hTv-4alvKYco88BsWL-_eKw',
    appId: '1:581288455500:web:412f12c1c553218807f3e9',
    messagingSenderId: '581288455500',
    projectId: 'mile-e1045',
    authDomain: 'mile-e1045.firebaseapp.com',
    storageBucket: 'mile-e1045.appspot.com',
    measurementId: 'G-XK8119ERNG',
  );

}